services:

  ciba-relying-party:
    build: ./ciba-relying-party
    image: demo/ciba-relying-party
    networks:
      - ciba-demo

  ciba-consumer:
    build: ./ciba-consumer
    image: demo/ciba-consumer
    ports:
      - "8001:8001"
    networks:
      - ciba-demo

  ciba-authenticator:
    build: ./ciba-authenticator
    image: demo/ciba-authenticator
    ports:
      - "8002:8002"
    networks:
      - ciba-demo

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"

      KC_HOSTNAME: "http://localhost:8080"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"

      KC_SPI_CIBA_AUTH_CHANNEL_CIBA_HTTP_AUTH_CHANNEL_HTTP_AUTHENTICATION_CHANNEL_URI: "http://ciba-relying-party:8000/auth"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - ciba-demo

networks:
  ciba-demo:
